"use client";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";
import AppContext from "./components/AppContext";
import toast, { Toaster } from "react-hot-toast";
import { useEffect } from "react";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useEffect(() => {
    const handleContextMenu = (event) => {
      event.preventDefault();
      toast("I know you can bypass this 👍");
    };

    document.addEventListener("contextmenu", handleContextMenu);

    return () => {
      document.removeEventListener("contextmenu", handleContextMenu);
    };
  }, []);
  return (
    <html lang="en" className="scroll-smooth">
      <body className={roboto.className}>
        <main className="max-w-4xl mx-auto  p-4">
          <AppContext>
            <Toaster></Toaster>
            <Header></Header>
            {children}
            <Footer></Footer>
          </AppContext>
        </main>
      </body>
    </html>
  );
}
